# Generated by Django 2.1.5 on 2019-01-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(db_index=True, max_length=511)),
                ('link', models.CharField(blank=True, max_length=1023, null=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
