# Generated by Django 2.1.5 on 2019-01-13 00:02

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogindexpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='subheadline',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
