# Generated by Django 2.1.5 on 2019-01-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogindexpage_subheadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='subheadline',
            field=models.CharField(max_length=127),
        ),
    ]
