# Generated by Django 2.1.5 on 2019-01-12 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(choices=[('impakt', 'Directly-supplied by Impakt researchers'), ('sustainalytics', 'Sustainalytics')], db_index=True, help_text='Where the information for this assessment came from', max_length=127, verbose_name='Data Source')),
                ('justification', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, help_text='Link users to more info about why Impakt gave this assessment', max_length=255, null=True)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], db_index=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('ASIN', models.CharField(blank=True, db_index=True, max_length=127, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.CharField(db_index=True, editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_image', models.ImageField(help_text='Icon to display when a company scores positively on this metric', upload_to='', verbose_name='Positive Image')),
                ('negative_image', models.ImageField(help_text='Icon to display when a company scores negatively on this metric', upload_to='')),
                ('neutral_image', models.ImageField(help_text='Icon to display when a company scores neutrally on this metric', upload_to='')),
                ('text', models.CharField(db_index=True, max_length=63)),
                ('parent', models.ForeignKey(blank=True, help_text='Which metric, if any, this metric should appear nested under in user dropdowns', null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Metric')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Metric'),
        ),
    ]
