# Generated by Django 2.1.5 on 2019-01-27 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20190123_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='sustainalytics_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('strongly_negative', 'Strongly Negative'), ('neutral', 'Neutral')], db_index=True, max_length=63),
        ),
        migrations.AddField(
            model_name='incident',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='incident',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Metric'),
        ),
    ]
