# Generated by Django 2.2 on 2019-04-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20190406_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='metric',
            options={'ordering': ['text']},
        ),
    ]
