# Generated by Django 2.1 on 2018-08-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180826_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='search_terms',
            field=models.ManyToManyField(to='products.SearchTerm'),
        ),
    ]
